#include<dos.h>
#include<iomanip.h>
#include<stdio.h>
#include<iostream.h>
#include<conio.h>
	void main() {
	clrscr();
	cout<<"\n feliz natal!!!!!";
delay(100);sound(1000);delay(300);nosound();delay(400);
sound(1000);delay(300);nosound();delay(400);sound(1002);delay(300);nosound();
delay(400);sound(1000);delay(400);nosound();delay(400);sound(1000);delay(400);
nosound();delay(400);sound(1000);delay(400);nosound();
sound(1000);delay(400);nosound();sound(1002);delay(700);nosound();
delay(100);sound(10000);delay(400);nosound();sound(1200);delay(300);nosound();
sound(800);delay(500);nosound();sound(900);delay(200);nosound();sound(1000);
delay(600);nosound();sound(1100);delay(400);nosound();sound(1100);delay(400);
sound(1080);delay(400);nosound();   }


