#include<iostream>
#include<conio.h>
#include<iomanip>
#include<dos.h>
#include<windows.h>
#include<locale.h>
#include<stdio.h>
#include<dos.h>
#include<string.h>
#include<ctype.h>
using namespace std;
int main() {
	system("cls");
cout<<"\xC9\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xBB\n";
cout<<"\xBA  FITO    \xBA\n";
cout<<"\xC8\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xCD\xBC\n";
	system("pause");   
       }
