#include<stdio.h>
#include<conio.h>
#include<dos.h>
#include<iostream.h>
#include<iomanip.h>
void main() {
clrscr();
int r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,num;
cout<<"\n digite um numero:";
cin>>num;
r1=num*1;r2=num*2;r3=num*3;r4=num*4;r5=num*5;r6=num*6;r7=num*7;r8=num*8;r9=num*9;r10=num*10;
cout<<"\n"<<num<<" * 1  ="<<r1;
cout<<"\n"<<num<<" * 2  ="<<r2;
cout<<"\n"<<num<<" * 3  ="<<r3;
cout<<"\n"<<num<<" * 4  ="<<r4;
cout<<"\n"<<num<<" * 5  ="<<r5;
cout<<"\n"<<num<<" * 6  ="<<r6;
cout<<"\n"<<num<<" * 7  ="<<r7;
cout<<"\n"<<num<<" * 8  ="<<r8;
cout<<"\n"<<num<<" * 9  ="<<r9;
cout<<"\n"<<num<<" * 10 ="<<r10;
getch();
}






